version: '3'

#networks:
#  loki:
#    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - loki
#    ports:
#      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file:
      - ./grafana.env
#    depends_on:
#      - prometheus
#    networks:
#      - loki
#    ports:
#      - 3000

#  loki:
#    image: grafana/loki
#    ports:
#      - 3100:3100
#
#  promtail:
#    image: grafana/promtail
#    container_name: promtail
#    volumes:
#      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
#    depends_on:
#      - loki
#    command: -config.file=/etc/promtail/promtail-config.yaml
