client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'service-one'
    static_configs:
      - targets: ['localhost:8080']
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message